2015/10/03 06:17:12 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\taller_auto\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\taller_auto\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/taller_auto/index.php?r=mecanico/index
HTTP_REFERER=http://localhost:8085/taller_auto/
---
2015/10/03 06:36:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/taller_auto/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php?r=gii/default/index
---
2015/10/03 06:37:05 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/taller_auto/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php?r=gii/default/index
---
2015/10/03 14:48:03 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\tallermecanica\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\tallermecanica\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/tallermecanica/index.php?r=mecanico/index
HTTP_REFERER=http://localhost/tallermecanica/
---
2015/10/14 06:06:39 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\taller_auto\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\taller_auto\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\taller_auto\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\taller_auto\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\taller_auto\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\taller_auto\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\taller_auto\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\taller_auto\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\taller_auto\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\taller_auto\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\taller_auto\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/taller_auto/index.php?r=mecanico/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php
---
2015/10/14 06:07:09 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\taller_auto\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\taller_auto\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\taller_auto\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\taller_auto\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\taller_auto\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\taller_auto\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\taller_auto\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\taller_auto\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\taller_auto\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\taller_auto\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\taller_auto\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/taller_auto/index.php?r=mecanico/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php
---
2015/10/14 06:07:31 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\taller_auto\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\taller_auto\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\taller_auto\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\taller_auto\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\taller_auto\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\taller_auto\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\taller_auto\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\taller_auto\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\taller_auto\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\taller_auto\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\taller_auto\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/taller_auto/index.php?r=mecanico/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php
---
2015/10/14 06:20:06 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\taller_auto\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\taller_auto\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\taller_auto\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\taller_auto\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\taller_auto\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\taller_auto\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\taller_auto\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\taller_auto\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\taller_auto\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\taller_auto\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\taller_auto\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/taller_auto/index.php?r=mecanico/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php?r=site/index
---
2015/10/14 06:20:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\taller_auto\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\taller_auto\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\taller_auto\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\taller_auto\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\taller_auto\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\taller_auto\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\taller_auto\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\taller_auto\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\taller_auto\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\taller_auto\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\taller_auto\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/taller_auto/index.php?r=mecanico/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php?r=site/index
---
2015/10/15 01:25:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\taller_auto\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\taller_auto\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/taller_auto/index.php?r=mecanico/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php
---
2015/10/15 01:37:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:37:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:37:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:37:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:37:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:37:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:38:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:38:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:38:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:39:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:39:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:39:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:39:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:39:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:39:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 02:14:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "sevicio/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('sevicio/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/sevicio/index.html
---
2015/10/22 02:41:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
